// Auto-generated: prefix RNNoise's Opus/CELT/DNN-derived symbols so they
// don't collide with libopus (swift-opus) at link time. Public rnnoise_*
// API is excluded. Regenerate if the vendored source/model changes.
#ifndef RNNOISE_SYMBOL_PREFIX_H
#define RNNOISE_SYMBOL_PREFIX_H
#define _celt_autocorr rnx__celt_autocorr
#define _celt_lpc rnx__celt_lpc
#define apply_window rnx_apply_window
#define biquad rnx_biquad
#define celt_fir rnx_celt_fir
#define celt_fir5 rnx_celt_fir5
#define celt_iir rnx_celt_iir
#define celt_inner_prod rnx_celt_inner_prod
#define celt_pitch_xcorr rnx_celt_pitch_xcorr
#define check_init rnx_check_init
#define compute_band_corr rnx_compute_band_corr
#define compute_band_energy rnx_compute_band_energy
#define compute_bitrev_table rnx_compute_bitrev_table
#define compute_dense rnx_compute_dense
#define compute_frame_features rnx_compute_frame_features
#define compute_gru rnx_compute_gru
#define compute_pitch_gain rnx_compute_pitch_gain
#define compute_rnn rnx_compute_rnn
#define compute_twiddles rnx_compute_twiddles
#define dct rnx_dct
#define denoise_gru rnx_denoise_gru
#define denoise_gru_bias rnx_denoise_gru_bias
#define denoise_gru_recurrent_weights rnx_denoise_gru_recurrent_weights
#define denoise_gru_weights rnx_denoise_gru_weights
#define denoise_output rnx_denoise_output
#define denoise_output_bias rnx_denoise_output_bias
#define denoise_output_weights rnx_denoise_output_weights
#define dual_inner_prod rnx_dual_inner_prod
#define eband5ms rnx_eband5ms
#define find_best_pitch rnx_find_best_pitch
#define forward_transform rnx_forward_transform
#define frame_analysis rnx_frame_analysis
#define frame_synthesis rnx_frame_synthesis
#define input_dense rnx_input_dense
#define input_dense_bias rnx_input_dense_bias
#define input_dense_weights rnx_input_dense_weights
#define interp_band_gain rnx_interp_band_gain
#define inverse_transform rnx_inverse_transform
#define kf_bfly2 rnx_kf_bfly2
#define kf_bfly3 rnx_kf_bfly3
#define kf_bfly4 rnx_kf_bfly4
#define kf_bfly5 rnx_kf_bfly5
#define kf_factor rnx_kf_factor
#define ltmp0 rnx_ltmp0
#define ltmp1 rnx_ltmp1
#define ltmp2 rnx_ltmp2
#define noise_gru rnx_noise_gru
#define noise_gru_bias rnx_noise_gru_bias
#define noise_gru_recurrent_weights rnx_noise_gru_recurrent_weights
#define noise_gru_weights rnx_noise_gru_weights
#define opus_fft_alloc rnx_opus_fft_alloc
#define opus_fft_alloc_arch_c rnx_opus_fft_alloc_arch_c
#define opus_fft_alloc_twiddles rnx_opus_fft_alloc_twiddles
#define opus_fft_c rnx_opus_fft_c
#define opus_fft_free rnx_opus_fft_free
#define opus_fft_free_arch_c rnx_opus_fft_free_arch_c
#define opus_fft_impl rnx_opus_fft_impl
#define opus_ifft_c rnx_opus_ifft_c
#define pitch_downsample rnx_pitch_downsample
#define pitch_filter rnx_pitch_filter
#define pitch_search rnx_pitch_search
#define relu rnx_relu
#define remove_doubling rnx_remove_doubling
#define second_check rnx_second_check
#define sigmoid_approx rnx_sigmoid_approx
#define tansig_approx rnx_tansig_approx
#define tansig_table rnx_tansig_table
#define vad_gru rnx_vad_gru
#define vad_gru_bias rnx_vad_gru_bias
#define vad_gru_recurrent_weights rnx_vad_gru_recurrent_weights
#define vad_gru_weights rnx_vad_gru_weights
#define vad_output rnx_vad_output
#define vad_output_bias rnx_vad_output_bias
#define vad_output_weights rnx_vad_output_weights
#define xcorr_kernel rnx_xcorr_kernel
#endif
